### ISSUE TITLE
nemos-images-minimal-lunar: qemu-arm64: build fails due to running out of space

### ISSUE THREAD

**Issue by IsaacJT** [Elektrobit/nemos-images#14]
When building nemos-images-minimal-lunar/qemu-arm64, Kiwi fails with the following error:

```
[ DEBUG   ]: 12:31:56 | EXEC: [rsync --archive --hard-links --xattrs --acls --one-file-system --inplace --exclude /efi/* /build/output/build/image-root/boot/ /var/tmp/kiwi_mount_manager.sz2m1wzs]
[ DEBUG   ]: 12:31:57 | EXEC: Failed with stderr: rsync: [receiver] write failed on "/var/tmp/kiwi_mount_manager.sz2m1wzs/bootargs.itb": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(380) [receiver=3.2.7]
rsync: [sender] write error: Broken pipe (32)
, stdout: (no output on stdout)
```

**Comment by IsaacJT** [comment]
Failure log: https://launchpadlibrarian.net/660024377/buildlog_ubuntu_lunar_arm64_nemos_BUILDING.txt.gz

**Comment by schaefi** [comment]
This happens if the size of the boot partition is not big enough to hold kernel/initrd and other data in /boot. In the image description we currently set

```
<type  ... filesystem="ext2" ... bootpartsize="100"/>
```

which means 100MB for an ext2 based /boot ~ 95MB free for data

I think the build fails because the kernel might have changed in size and modules, just guessing though. As part of the kiwi build process the initrd is created by kiwi via dracut which includes kernel modules and their dependencies. Thus the size constraints may vary according to the used kernel and module packages.

Solutions are:

* Increase the bootpartition size ... probably not what we want ?
* Check why kernel and initrd sizes have changed and maybe adapt ?

**Comment by IsaacJT** [comment]
It's likely because of the jump from kernel 6.1 to 6.2 in Lunar - I assume there's a bit more code/few more modules that've been added. 

I'll switch the kernel to the S32G kernel which we've now built to additionally support QEMU when I find time.

**Comment by IsaacJT** [comment]
No longer an issue
